use Hotel

insert into Temporada values (1, 'Otoño 2019', '2019-09-21', '2019-12-20')
insert into Temporada values (2, 'Invierno 2019', '2019-12-21', '2020-03-20')
insert into Temporada values (3, 'Primavera 2020', '2020-03-21', '2020-06-20')
insert into Temporada values (4, 'Verano 2020', '2020-06-21', '2020-09-20')

insert into Pais values (1, 'Alemania')
insert into Pais values (2, 'Argentina')
insert into Pais values (3, 'Brasil')
insert into Pais values (4, 'Canada')
insert into Pais values (5, 'Chile')
insert into Pais values (6, 'China')
insert into Pais values (7, 'Colombia')
insert into Pais values (8, 'Corea del Norte')
insert into Pais values (9, 'Corea del Sur')
insert into Pais values (10, 'Costa Rica')
insert into Pais values (11, 'Egipto')
insert into Pais values (12, 'España')
insert into Pais values (13, 'Estados Unidos')
insert into Pais values (14, 'Francia')
insert into Pais values (15, 'India')
insert into Pais values (16, 'Italia')
insert into Pais values (17, 'Japon')
insert into Pais values (18, 'Mexico')
insert into Pais values (19, 'Nigeria')
insert into Pais values (20, 'Paises Bajos')
insert into Pais values (21, 'Polonia')
insert into Pais values (22, 'Portugal')
insert into Pais values (23, 'Reino Unido')
insert into Pais values (24, 'Rusia')
insert into Pais values (25, 'Uruguay')

insert into Estado values (1, 'Berlin') 
insert into Estado values (2, 'Hamburgo') 
insert into Estado values (3, 'Buenos Aires')
insert into Estado values (4, 'Cordoba')
insert into Estado values (5, 'Brasilia')
insert into Estado values (6, 'Rio de Janeiro')
insert into Estado values (7, 'Ottawa')
insert into Estado values (8, 'Toronto')
insert into Estado values (9, 'Santiago')
insert into Estado values (10, 'Valparaiso')
insert into Estado values (11, 'Pekin')
insert into Estado values (12, 'Shangai')
insert into Estado values (13, 'Bogota')
insert into Estado values (14, 'Bolivar')
insert into Estado values (15, 'Pionyang')
insert into Estado values (16, 'Rason')
insert into Estado values (17, 'Seul')
insert into Estado values (18, 'Busan')
insert into Estado values (19, 'San Jose')
insert into Estado values (20, 'Alajuela')
insert into Estado values (21, 'El Cairo') 
insert into Estado values (22, 'Mar Rojo') 
insert into Estado values (23, 'Madrid')
insert into Estado values (24, 'Cataluña')
insert into Estado values (25, 'Washington')
insert into Estado values (26, 'Nueva York')
insert into Estado values (27, 'Paris')
insert into Estado values (28, 'Lyon') 
insert into Estado values (29, 'Nueva Delhi')
insert into Estado values (30, 'Guyarat')
insert into Estado values (31, 'Roma')
insert into Estado values (32, 'Milan')
 
insert into Estado values (33, 'Tokio')
insert into Estado values (34, 'Osaka')
insert into Estado values (35, 'Ciudad de México')
insert into Estado values (36, 'Nuevo Leon')
insert into Estado values (37, 'Abuya')
insert into Estado values (38, 'Niger')
insert into Estado values (39, 'Ámsterdam')
insert into Estado values (40, 'Roterdam')
insert into Estado values (41, 'Varsovia') 
insert into Estado values (42, 'Lublin') 
insert into Estado values (43, 'Lisboa')
insert into Estado values (44, 'Oporto')
insert into Estado values (45, 'Londres')
insert into Estado values (46, 'Manchester')
insert into Estado values (47, 'Moscu')
insert into Estado values (48, 'Leningrado')
insert into Estado values (49, 'Montevideo')
insert into Estado values (50, 'Salto')

insert into Ciudad values (1, 'Monterrey')
insert into Ciudad values (2, 'San Nicolas')
insert into Ciudad values (3, 'Ciudad3')
insert into Ciudad values (4, 'Ciudad4')
insert into Ciudad values (5, 'Ciudad5')
insert into Ciudad values (6, 'Ciudad6')
insert into Ciudad values (7, 'Ciudad7')
insert into Ciudad values (8, 'Ciudad8')
insert into Ciudad values (9, 'Ciudad9')
insert into Ciudad values (10, 'Ciudad10')
insert into Ciudad values (11, 'Ciudad11')
insert into Ciudad values (12, 'Ciudad12')

insert into Estado_Habitacion values (1, 'Disponible')
insert into Estado_Habitacion values (2, 'Ocupado')

insert into Tipo_Habitacion values (1, 'Individual', 'Habitacion para 1 persona con baño, aire acondicionado y calefacción', 1, 1100)
insert into Tipo_Habitacion values (2, 'Doble', 'Habitacion para 2 personas con baño, aire acondicionado y calefacción', 2, 1500)
insert into Tipo_Habitacion values (3, 'Matrimonial', 'Habitacion con 2 camas matrimonial, baño, aire acondicionado y calefacción', 4, 1900)
insert into Tipo_Habitacion values (4, 'Suite', 'Habitacion con un sofacama, comedor, oficina y cocina', 4, 2200)

insert into Tipo_Servicios values (1, 'Desayuno')
insert into Tipo_Servicios values (2, 'Piscina')
insert into Tipo_Servicios values (3, 'Spa')
insert into Tipo_Servicios values (4, 'Wi-fi')
insert into Tipo_Servicios values (5, 'Bar')

insert into Servicios values(1, 1, '2019-09-21', 300)
insert into Servicios values(2, 1, '2019-12-21', 300)
insert into Servicios values(3, 1, '2020-03-21', 300)
insert into Servicios values(4, 1, '2020-06-21', 300)
insert into Servicios values(5, 2, '2019-09-21', 1200)
insert into Servicios values(6, 2, '2019-12-21', 500)
insert into Servicios values(7, 2, '2020-03-21', 1700)
insert into Servicios values(8, 2, '2020-06-21', 1500)
insert into Servicios values(9, 3, '2019-09-21', 1100)
insert into Servicios values(10, 3, '2019-12-21', 1100)
insert into Servicios values(11, 3, '2020-03-21', 1100)
insert into Servicios values(12, 3, '2020-06-21', 1100)
insert into Servicios values(13, 4, '2019-09-21', 400)
insert into Servicios values(14, 4, '2019-12-21', 400)
insert into Servicios values(15, 4, '2020-03-21', 400)
insert into Servicios values(16, 4, '2020-06-21', 400)
insert into Servicios values(17, 5, '2019-09-21', 750)
insert into Servicios values(18, 5, '2019-12-21', 750)
insert into Servicios values(19, 5, '2020-03-21', 750)
insert into Servicios values(20, 5, '2020-06-21', 750)

insert into Metodo_Pago values (1, 1, 'Aerolinea')
insert into Metodo_Pago values (2, 2, 'Aerolinea')
insert into Metodo_Pago values (3, 3, 'Viajes (American Express)')
insert into Metodo_Pago values (4, 4, 'Bancos (Visa)')
insert into Metodo_Pago values (5, 5, 'Bancos (Mastercard)')
insert into Metodo_Pago values (6, 6, 'Bancos (Otros)')
insert into Metodo_Pago values (7, 7, 'Sector petrolífero')
insert into Metodo_Pago values (8, 8, 'Telecomunicacion')
insert into Metodo_Pago values (9, 9, 'Asignacion Nacional')

insert into Hotel values (1, 'Hack-Inn', '5 estrellas', 18, 36, 2, 'Ave. Universidad Norte 101', 66450, 81580000, 'hackinn@hotmail.com', 'Hotel perteneciente a International Hotel Group')

insert into Puesto_Empleado values (1, 'Recepcion', 'Se encargan de llever el registro de entradas y salidas del hotel ', 7000)
insert into Puesto_Empleado values (2, 'Limpieza', 'Se encargan de mantener la higiene de las habitaciones ', 3000)
insert into Puesto_Empleado values (3, 'Gerente', 'Responsable del funcionamiento general del hotel y de la calidad del servicio', 10000)
insert into Puesto_Empleado values (4, 'Boton', 'Se encarga de recibir a los huespedes, asistirlos en cuanto a su equipaje y guiarlos hasta su habitación', 5000)

insert into Habitaciones values (1, 1, 1, 'Habitacion perteneciente al primer piso del hotel')
insert into Habitaciones values (2, 1, 1, 'Habitacion perteneciente al primer piso del hotel')
insert into Habitaciones values (3, 1, 2, 'Habitacion perteneciente al primer piso del hotel')
insert into Habitaciones values (4, 1, 1, 'Habitacion perteneciente al primer piso del hotel')
insert into Habitaciones values (5, 1, 1, 'Habitacion perteneciente al primer piso del hotel')
insert into Habitaciones values (6, 1, 1, 'Habitacion perteneciente al primer piso del hotel')
insert into Habitaciones values (7, 1, 1, 'Habitacion perteneciente al primer piso del hotel')
insert into Habitaciones values (8, 1, 2, 'Habitacion perteneciente al primer piso del hotel')
insert into Habitaciones values (9, 1, 1, 'Habitacion perteneciente al primer piso del hotel')
insert into Habitaciones values (10, 1, 1, 'Habitacion perteneciente al primer piso del hotel')
insert into Habitaciones values (11, 2, 1, 'Habitacion perteneciente al segundo piso del hotel')
insert into Habitaciones values (12, 2, 1, 'Habitacion perteneciente al segundo piso del hotel')
insert into Habitaciones values (13, 2, 1, 'Habitacion perteneciente al segundo piso del hotel')
insert into Habitaciones values (14, 2, 1, 'Habitacion perteneciente al segundo piso del hotel')
insert into Habitaciones values (15, 2, 1, 'Habitacion perteneciente al segundo piso del hotel')
insert into Habitaciones values (16, 2, 1, 'Habitacion perteneciente al segundo piso del hotel')
insert into Habitaciones values (17, 2, 2, 'Habitacion perteneciente al segundo piso del hotel')
insert into Habitaciones values (18, 2, 1, 'Habitacion perteneciente al segundo piso del hotel')
insert into Habitaciones values (19, 2, 1, 'Habitacion perteneciente al segundo piso del hotel')
insert into Habitaciones values (20, 2, 1, 'Habitacion perteneciente al segundo piso del hotel')
insert into Habitaciones values (21, 3, 1, 'Habitacion perteneciente al tercer piso del hotel')
insert into Habitaciones values (22, 3, 1, 'Habitacion perteneciente al tercer piso del hotel')
insert into Habitaciones values (23, 3, 1, 'Habitacion perteneciente al tercer piso del hotel')
insert into Habitaciones values (24, 3, 2, 'Habitacion perteneciente al tercer piso del hotel')
insert into Habitaciones values (25, 3, 1, 'Habitacion perteneciente al tercer piso del hotel')
insert into Habitaciones values (26, 3, 1, 'Habitacion perteneciente al tercer piso del hotel')
insert into Habitaciones values (27, 3, 1, 'Habitacion perteneciente al tercer piso del hotel')
insert into Habitaciones values (28, 3, 1, 'Habitacion perteneciente al tercer piso del hotel')
insert into Habitaciones values (29, 3, 1, 'Habitacion perteneciente al tercer piso del hotel')
insert into Habitaciones values (30, 3, 1, 'Habitacion perteneciente al tercer piso del hotel')
insert into Habitaciones values (31, 4, 1, 'Habitacion perteneciente al cuarto piso del hotel')
insert into Habitaciones values (32, 4, 2, 'Habitacion perteneciente al cuarto piso del hotel')
insert into Habitaciones values (33, 4, 1, 'Habitacion perteneciente al cuarto piso del hotel')
insert into Habitaciones values (34, 4, 1, 'Habitacion perteneciente al cuarto piso del hotel')
insert into Habitaciones values (35, 4, 1, 'Habitacion perteneciente al cuarto piso del hotel')
insert into Habitaciones values (36, 4, 1, 'Habitacion perteneciente al cuarto piso del hotel')
insert into Habitaciones values (37, 4, 1, 'Habitacion perteneciente al cuarto piso del hotel')
insert into Habitaciones values (38, 4, 1, 'Habitacion perteneciente al cuarto piso del hotel')
insert into Habitaciones values (39, 4, 1, 'Habitacion perteneciente al cuarto piso del hotel')
insert into Habitaciones values (40, 4, 1, 'Habitacion perteneciente al cuarto piso del hotel')

insert into Empleados values (1, 'Alexis', 'Bliss', 'Kaufman', 28, 4, 7, 3, 'Canada Pl #404', 999, 42020899, 'lexikauf@hotmail.com', 2) 
insert into Empleados values (2, 'Manuel', 'Andrade', 'Oropeza', 29, 18, 35, 3, 'Dr. Andrade 140-A', 06720, 55789140, 'mannyandrade@hotmail.com', 3) 
insert into Empleados values (3, 'Catherine', 'Joy', 'Perry', 31, 24, 47, 6, 'Nevsky Ave 56', 19101, 24566666, 'catjp@hotmail.com', 1) 
insert into Empleados values (4, 'Ammanda', 'Rose', ' Saccomanno', 28, 16, 31, 6, 'Alcamo TP 66', 91011, 23516024, 'amros@hotmail.com', 2) 
insert into Empleados values (5, 'Colby', 'Rollins', 'Lopez', 33, 13, 26, 3, '1290 6th Ave 2nd Floo', 10104, 22227000, 'colbyrl@hotmail.com', 4) 


insert into Huesped values (1, 'Allen', 'Styles', 'Jones', 42, 13, 26, 3, '1203 Zaragoza St', 78040, 63079168, 'ajph1@hotmail.com') 
insert into Huesped values (2, 'Rebecca', 'Lynch', ' Quin', 32, 23, 45, 6, ' 88 High St', 78040, 0 123 5986, 'beclyn@hotmail.com') 
insert into Huesped values (3, 'Ashley', 'Flair', 'Raymond', 33, 14, 27, 6, '36 Rue dAboukir', 75002, 84429279, 'asfli@hotmail.com') 
insert into Huesped values (4, 'Bryan', 'Loyd', 'Danielson', 38, 13, 26, 3, '360 Rainbow Blvd', 14303, 63043622, 'brydan@hotmail.com') 
insert into Huesped values (5, 'Jeffrey', 'Hardy', 'Nero', 42, 2, 3, 3, 'Av. de los Incas 4672', 14274, 44235124, 'jeffhn@hotmail.com') 


insert into Reservaciones values (1, 3, 1, 1, 3, '2020-06-02', '2020-06-04', 24, 11, 2, 3000, 'Vacaciones', 'Sin descripción extra')
insert into Reservaciones values (2, 2, 1, 2, 1, '2020-01-30', '2020-01-31', 8, 2, 3, 1500, 'Trabajo', 'Sin descripción extra')
insert into Reservaciones values (3, 3, 1, 3, 4, '2020-04-05', '2020-04-08', 32, 7, 4, 4000, 'Vacaciones', 'Sin descripción extra')
insert into Reservaciones values (4, 3, 1, 4, 1, '2020-05-22', '2020-05-27', 3, 15, 5, 1500, 'Trabajo', 'Sin descripción extra')
insert into Reservaciones values (5, 4, 1, 5, 2, '2020-08-31', '2020-09-05', 17, 20, 6, 2300, 'Vacaciones', 'Sin descripción extra')

update Ciudad set Nombre_Ciudad = 'Ciudad No Asignada (America)' where Nombre_Ciudad = 'Ciudad3'
update Ciudad set Nombre_Ciudad = 'Ciudad No Asignada (Asia)' where Nombre_Ciudad = 'Ciudad4'
update Ciudad set Nombre_Ciudad = 'Ciudad No Asignada (Africa)' where Nombre_Ciudad = 'Ciudad5'
update Ciudad set Nombre_Ciudad = 'Ciudad No Asignada (Europa)' where Nombre_Ciudad = 'Ciudad6'
update Ciudad set Nombre_Ciudad = 'Ciudad No Asignada (Oceania)' where Nombre_Ciudad = 'Ciudad7'

delete from Ciudad where Nombre_Ciudad = 'Ciudad8'
delete from Ciudad where Nombre_Ciudad = 'Ciudad9'
delete from Ciudad where Nombre_Ciudad = 'Ciudad10'
delete from Ciudad where Nombre_Ciudad = 'Ciudad11'
delete from Ciudad where Nombre_Ciudad = 'Ciudad12'




